#!/bin/sh

set -e

# Cross platforms

set -- \
x86_64-unknown-freebsd \
x86_64-unknown-netbsd

for platform do
  echo "$platform"
  cross build --release --target "$platform"
done

# Native platforms
# rustup target add arm-unknown-linux-gnueabihf
# rustup target add x86_64-unknown-linux-musl

set -- \
arm-unknown-linux-gnueabihf \
x86_64-unknown-linux-musl \

for platform do
  echo "$platform"
  cargo build --release --target "$platform"
done
